"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.providerOrderRouter = void 0;
var express_1 = require("express");
var auth_1 = require("../../../middleware/auth");
var provider_order_controller_1 = require("./provider.order.controller");
var router = (0, express_1.Router)();
router.get("/orders", (0, auth_1.default)(auth_1.UserRole.PROVIDER), provider_order_controller_1.getProviderOrders);
router.patch("/orders/:id", (0, auth_1.default)(auth_1.UserRole.PROVIDER), provider_order_controller_1.updateOrderStatus);
exports.providerOrderRouter = router;
